/* OCWS Theme Engine — Load themes from themes/ directory and generate CSS
 *
 * This tool reads INI theme profiles (themes/*.ini) and generates:
 *   1. tokens.css — CSS custom properties for GTK widgets
 *   2. ocws.css — Glassmorphic panel styles
 *   3. GTK CSS — Application theming
 *
 * Usage:
 *   ocws-style <theme.ini>              Generate all CSS files
 *   ocws-style <theme.ini> --tokens     Generate tokens.css only
 *   ocws-style <theme.ini> --preview    Print CSS to stdout
 * ============================================================ */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <unistd.h>
#include <sys/wait.h>

#define MAX_ENTRIES 128
#define KEY_LEN 64
#define VAL_LEN 256

typedef struct {
    char key[KEY_LEN];
    char value[VAL_LEN];
} ini_entry_t;

static ini_entry_t entries[MAX_ENTRIES];
static int entry_count = 0;

static char* strtrim(char* s) {
    while (*s && isspace(*s)) s++;
    char* end = s + strlen(s) - 1;
    while (end > s && isspace(*end)) *end-- = '\0';
    return s;
}

static void ini_load(const char* path) {
    FILE* f = fopen(path, "r");
    if (!f) { fprintf(stderr, "Cannot open %s\n", path); return; }

    char line[512];
    char section[64] = "";
    while (fgets(line, sizeof(line), f)) {
        char* s = strtrim(line);
        if (*s == ';' || *s == '\0') continue;

        if (*s == '[') {
            char* end = strchr(s, ']');
            if (end) {
                *end = '\0';
                snprintf(section, sizeof(section), "%s.", s + 1);
            }
            continue;
        }

        char* eq = strchr(s, '=');
        if (!eq) continue;

        *eq = '\0';
        char* key = strtrim(s);
        char* val = strtrim(eq + 1);

        if (entry_count < MAX_ENTRIES) {
            snprintf(entries[entry_count].key, KEY_LEN, "%s%s", section, key);
            snprintf(entries[entry_count].value, VAL_LEN, "%s", val);
            entry_count++;
        }
    }
    fclose(f);
}

static const char* ini_get(const char* key, const char* fallback) {
    for (int i = 0; i < entry_count; i++) {
        if (strcmp(entries[i].key, key) == 0)
            return entries[i].value;
    }
    return fallback;
}

static void write_tokens_css(const char* output_dir) {
    char path[512];
    snprintf(path, sizeof(path), "%s/tokens.css", output_dir);

    FILE* f = fopen(path, "w");
    if (!f) { fprintf(stderr, "Cannot write %s\n", path); return; }

    const char* name = ini_get("meta.name", "Unknown");

    fprintf(f, "/* OCWS CSS Tokens — Generated by ocws-style\n");
    fprintf(f, " * Theme: %s\n", name);
    fprintf(f, " * Do NOT edit manually — regenerate with: ocws-style <theme.ini>\n */\n\n");

    /* Base colors */
    fprintf(f, "@define-color ocws_bg %s;\n", ini_get("colors.base", "#1e1e2e"));
    fprintf(f, "@define-color ocws_fg %s;\n", ini_get("colors.text", "#cdd6f4"));
    fprintf(f, "@define-color ocws_mantle %s;\n", ini_get("colors.mantle", "#181825"));
    fprintf(f, "@define-color ocws_crust %s;\n", ini_get("colors.crust", "#11111b"));
    fprintf(f, "\n");

    /* Surface colors */
    fprintf(f, "@define-color ocws_surface0 %s;\n", ini_get("colors.surface0", "#313244"));
    fprintf(f, "@define-color ocws_surface1 %s;\n", ini_get("colors.surface1", "#45475a"));
    fprintf(f, "@define-color ocws_surface2 %s;\n", ini_get("colors.surface2", "#585b70"));
    fprintf(f, "\n");

    /* Overlay colors */
    fprintf(f, "@define-color ocws_overlay0 %s;\n", ini_get("colors.overlay0", "#6c7086"));
    fprintf(f, "@define-color ocws_overlay1 %s;\n", ini_get("colors.overlay1", "#7f849c"));
    fprintf(f, "@define-color ocws_overlay2 %s;\n", ini_get("colors.overlay2", "#9399b2"));
    fprintf(f, "\n");

    /* Text colors */
    fprintf(f, "@define-color ocws_subtext0 %s;\n", ini_get("colors.subtext0", "#a6adc8"));
    fprintf(f, "@define-color ocws_subtext1 %s;\n", ini_get("colors.subtext1", "#bac2de"));
    fprintf(f, "@define-color ocws_text %s;\n", ini_get("colors.text", "#cdd6f4"));
    fprintf(f, "\n");

    /* Accent colors */
    fprintf(f, "@define-color ocws_blue %s;\n", ini_get("colors.blue", "#89b4fa"));
    fprintf(f, "@define-color ocws_sapphire %s;\n", ini_get("colors.sapphire", "#74c7ec"));
    fprintf(f, "@define-color ocws_sky %s;\n", ini_get("colors.sky", "#89dceb"));
    fprintf(f, "@define-color ocws_teal %s;\n", ini_get("colors.teal", "#94e2d5"));
    fprintf(f, "@define-color ocws_green %s;\n", ini_get("colors.green", "#a6e3a1"));
    fprintf(f, "@define-color ocws_yellow %s;\n", ini_get("colors.yellow", "#f9e2af"));
    fprintf(f, "@define-color ocws_peach %s;\n", ini_get("colors.peach", "#fab387"));
    fprintf(f, "@define-color ocws_maroon %s;\n", ini_get("colors.maroon", "#eba0ac"));
    fprintf(f, "@define-color ocws_red %s;\n", ini_get("colors.red", "#f38ba8"));
    fprintf(f, "@define-color ocws_mauve %s;\n", ini_get("colors.mauve", "#cba6f7"));
    fprintf(f, "@define-color ocws_pink %s;\n", ini_get("colors.pink", "#f5c2e7"));
    fprintf(f, "@define-color ocws_flamingo %s;\n", ini_get("colors.flamingo", "#f2cdcd"));
    fprintf(f, "@define-color ocws_rosewater %s;\n", ini_get("colors.rosewater", "#f5e0dc"));
    fprintf(f, "@define-color ocws_lavender %s;\n", ini_get("colors.lavender", "#b4befe"));
    fprintf(f, "\n");

    /* Semantic aliases */
    fprintf(f, "@define-color ocws_accent %s;\n", ini_get("colors.blue", "#89b4fa"));
    fprintf(f, "@define-color ocws_urgent %s;\n", ini_get("colors.red", "#f38ba8"));
    fprintf(f, "@define-color ocws_warning %s;\n", ini_get("colors.yellow", "#f9e2af"));
    fprintf(f, "@define-color ocws_ok %s;\n", ini_get("colors.green", "#a6e3a1"));
    fprintf(f, "@define-color ocws_info %s;\n", ini_get("colors.sky", "#89dceb"));
    fprintf(f, "@define-color ocws_muted %s;\n", ini_get("colors.overlay0", "#6c7086"));
    fprintf(f, "\n");

    /* Alpha variants */
    const char* bg = ini_get("colors.base", "#1e1e2e");
    const char* fg = ini_get("colors.text", "#cdd6f4");
    const char* s0 = ini_get("colors.surface0", "#313244");
    const char* s1 = ini_get("colors.surface1", "#45475a");
    const char* accent = ini_get("colors.blue", "#89b4fa");
    const char* urgent = ini_get("colors.red", "#f38ba8");

    fprintf(f, "@define-color ocws_surface0_alpha50 alpha(%s, 0.5);\n", s0);
    fprintf(f, "@define-color ocws_surface1_alpha30 alpha(%s, 0.3);\n", s1);
    fprintf(f, "@define-color ocws_surface1_alpha50 alpha(%s, 0.5);\n", s1);
    fprintf(f, "@define-color ocws_surface2_alpha30 alpha(%s, 0.3);\n", ini_get("colors.surface2", "#585b70"));
    fprintf(f, "@define-color ocws_bg_alpha85 alpha(%s, 0.85);\n", bg);
    fprintf(f, "@define-color ocws_bg_alpha92 alpha(%s, 0.92);\n", bg);
    fprintf(f, "@define-color ocws_bg_alpha95 alpha(%s, 0.95);\n", bg);
    fprintf(f, "@define-color ocws_fg_alpha30 alpha(%s, 0.3);\n", fg);
    fprintf(f, "@define-color ocws_fg_alpha50 alpha(%s, 0.5);\n", fg);
    fprintf(f, "@define-color ocws_fg_alpha60 alpha(%s, 0.6);\n", fg);
    fprintf(f, "@define-color ocws_accent_alpha15 alpha(%s, 0.15);\n", accent);
    fprintf(f, "@define-color ocws_accent_alpha20 alpha(%s, 0.2);\n", accent);
    fprintf(f, "@define-color ocws_urgent_alpha15 alpha(%s, 0.15);\n", urgent);
    fprintf(f, "@define-color ocws_urgent_alpha20 alpha(%s, 0.2);\n", urgent);

    fclose(f);
    printf("Generated: %s\n", path);
}

int main(int argc, char **argv) {
    (void)argc;
    (void)argv;
    if (argc < 2) {
        fprintf(stderr, "Usage: %s <theme.ini> [--tokens|--preview]\n", argv[0]);
        return 1;
    }

    ini_load(argv[1]);

    const char* home = getenv("HOME");
    if (!home) home = "/tmp";

    char output_dir[512];
    snprintf(output_dir, sizeof(output_dir), "%s/.config/ocws", home);

    /* Ensure output directory exists */
    pid_t pid = fork();
    if (pid == 0) {
        execlp("mkdir", "mkdir", "-p", output_dir, NULL);
        exit(1);
    }
    waitpid(pid, NULL, 0);

    int tokens_only = (argc > 2 && strcmp(argv[2], "--tokens") == 0);
    int preview = (argc > 2 && strcmp(argv[2], "--preview") == 0);

    if (preview) {
        /* Print tokens to stdout */
        write_tokens_css("/tmp");
        FILE* f = fopen("/tmp/tokens.css", "r");
        if (f) {
            char buf[4096];
            size_t n;
            while ((n = fread(buf, 1, sizeof(buf), f)) > 0)
                fwrite(buf, 1, n, stdout);
            fclose(f);
        }
        return 0;
    }

    write_tokens_css(output_dir);

    if (!tokens_only) {
        printf("Theme '%s' applied successfully.\n", ini_get("meta.name", "Unknown"));
        printf("Run 'theme-engine.sh apply themes/<name>.ini' for full system theming.\n");
    }

    return 0;
}
