  [1;33m⚠[0m Unknown template variable: {{QT_ICON_THEME}}
  [1;33m⚠[0m Unknown template variable: {{QT_COLOR_SCHEME}}
  [1;33m⚠[0m Unknown template variable: {{QT_STANDARD_DIALOGS}}
  [1;33m⚠[0m Unknown template variable: {{QT_FONT}}
  [1;33m⚠[0m Unknown template variable: {{QT_MONO_FONT}}
[General]
icon_theme=
color_scheme=
standard_dialogs=

[Interface]
font=
monoFont=
